### PR TITLE
Testing PR with Jenkins.

### PR DESCRIPTION
**Pull request by jairideout**

### CODE REVIEW

**Comment by jairideout** [comment]
Build results will soon be (or already are) available at: http://23.21.234.210:8080/job/Clout/56/

**Comment by ghost** [comment]
Build results will soon be (or already are) available at: http://23.21.234.210:8080/job/clout-github-pr/5/

**Comment by ghost** [comment]
Build results will soon be (or already are) available at: http://23.21.234.210:8080/job/clout-github-pr/7/

**Comment by jairideout** [comment]
Please ignore this pull request. I'm using it to test out GitHub pull request integration with Jenkins.

**Comment by ghost** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/clout-github-pr/2/

**Pull request closed without merging**
